Fix incorrect iteration over a C array
Found by Clang 10:

 error: expression does not compute the number of elements in this array; element type is 'const MapStyleData',
 not 'QGeoMapType::MapStyle' [- Werror,-Wsizeof-array-div]

Instead, just use range-for.

Task-number: QTBUG-83666
Change-Id: I99ab0f318b1c43b89888fffd160b589c5543b9d4
Coverity-Id: 226105
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit 275efcc6c493e01fcbb623de4a277cffd584fa58)