Fix Clang 10 warnings about deprecated copy constructors
qgeocodereplyosm.cpp:115:21: error: loop variable 'k' of type 'const QString' creates a copy from type 'const QString' [-Werror,-Wrange-loop- construct]

Task-number: QTBUG-83666
Change-Id: I99ab0f318b1c43b89888fffd160b4a12bee11723
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
(cherry picked from commit 8b0c9024b1eb9b6a4ad2e440d6e7856ca3a09e80)
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>