Fix change-of-sign warning
 qdeclarativegeoroute_p.h(102): error #68: integer conversion resulted in a change of sign
      void initSegments(unsigned int lastIndex = -1);
                                                 ^

Change-Id: I052407b777ec43f78378fffd15311bd2bb1cdfdc
Reviewed-by: Alex Blasche <alexander.blasche@qt.io>