constructRoute: remove segmentPathLengthCount
It was causing a (fatal) warning:
error: variable 'segmentPathLengthCount' set but not used
[-Werror,-Wunused-but-set-variable]

Change-Id: Ia6ce5861539f878c307630182eb671c442d14a62
Reviewed-by: Lauri Laanmets <lauri.laanmets@eesti.ee>
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit 776a0cbbab7c4980bd50ec8dcb5c489857b08758)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>