Add unnecessary break to keep GCC 7 happy
Falling through or breaking have the same effect, since the next case
label repeats the same condition in the "if", which must necessarily be
false for the code to have fallen through.

qdeclarativesearchresultmodel.cpp:632:9: error: this statement may fall through [-Werror=implicit-fallthrough=]

Change-Id: Ia3e896da908f42939148fffd14c48127381f219d
Reviewed-by: Alex Blasche <alexander.blasche@qt.io>